import type { Donation } from './types';

export const donations: Donation[] = [
  {
    id: '1',
    title: 'Fauteuil vintage en cuir',
    description: 'Confortable et en bon état, quelques signes d\'usure.',
    category: 'Mobilier',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'leather armchair',
    user: {
      name: 'Alice Martin',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-22T10:00:00Z',
  },
  {
    id: '2',
    title: 'Collection de vinyles',
    description: 'Rock classique des années 70-80. Une dizaine d\'albums.',
    category: 'Musique',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'vinyl records',
    user: {
      name: 'Bob Garcia',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-22T09:30:00Z',
  },
  {
    id: '3',
    title: 'Vélo de ville hollandais',
    description: 'Nécessite une petite révision (pneus dégonflés).',
    category: 'Sport',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'city bike',
    user: {
      name: 'Claire Dubois',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-21T18:45:00Z',
  },
  {
    id: '4',
    title: 'Lampe de bureau design',
    description: 'Style industriel, fonctionne parfaitement.',
    category: 'Décoration',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'desk lamp',
    user: {
      name: 'David Petit',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-21T15:20:00Z',
  },
  {
    id: '5',
    title: 'Plantes vertes d\'intérieur',
    description: 'Lot de 3 plantes (Ficus, Monstera, Pothos).',
    category: 'Jardinage',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'house plants',
    user: {
      name: 'Eve Bernard',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-20T11:05:00Z',
  },
  {
    id: '6',
    title: 'Miroir ancien avec cadre doré',
    description: 'Très grand, parfait pour une entrée ou une chambre.',
    category: 'Décoration',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'antique mirror',
    user: {
      name: 'Frank Moreau',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-20T08:00:00Z',
  },
  {
    id: '7',
    title: 'Service à vaisselle complet',
    description: 'Pour 6 personnes, style rustique, très peu servi.',
    category: 'Cuisine',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dinnerware set',
    user: {
      name: 'Grace Lambert',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-19T20:15:00Z',
  },
  {
    id: '8',
    title: 'Guitare acoustique',
    description: 'Idéale pour débutants, avec sa housse de transport.',
    category: 'Musique',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'acoustic guitar',
    user: {
      name: 'Heidi Roux',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-18T14:30:00Z',
  },
    {
    id: '9',
    title: 'Machine à café à grains',
    description: 'Modèle automatique, a besoin d\'un détartrage.',
    category: 'Cuisine',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'coffee machine',
    user: {
      name: 'Ivan Lefevre',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-17T12:00:00Z',
  },
  {
    id: '10',
    title: 'Tapis berbère',
    description: '150x200cm, en laine, à nettoyer.',
    category: 'Décoration',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'berber rug',
    user: {
      name: 'Judy Marchand',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    createdAt: '2024-07-16T19:50:00Z',
  },
];
